Making scrypt more dynamic
libeclipse/pocket pull request #6
Opened 2017-01-12 22:48 UTC by libeclipse

A couple of changes to make scrypt cost-factors more dynamic and even allow user configuration.

2017-01-13 16:40 UTC, tobbbles submitted a review, later dismissed

2017-01-13 16:40 UTC, tobbbles commented on crypto/crypto.go
> +func DeriveKey(password, identifier []byte, N uint) []byte {
argument names should be lowercase

2017-01-13 16:42 UTC, awnumar commented on crypto/crypto.go
> +func DeriveKey(password, identifier []byte, N uint) []byte {
Not that argument. Scrypt's r and p can be lowercase, but N is capitalised.

2017-01-16 20:33 UTC, tobbbles commented on crypto/crypto.go
> +	derivedKey, _ := scrypt.Key(password, identifier, 1<<uint(costFactor["N"]), costFactor["r"], costFactor["p"], 32)
If costFactor[X] isn't set it'll default to the null value of int (zero) - do you want to add checks here to ensure the values are present?

2017-01-16 20:36 UTC, libeclipse commented on crypto/crypto.go
> +	derivedKey, _ := scrypt.Key(password, identifier, 1<<uint(costFactor["N"]), costFactor["r"], costFactor["p"], 32)
🤔 Well there's a default set in `pocket.go` so the only way the value would be zero would be if the user manually and explicitly sets it to zero. Not sure if I should disallow that. Scrypt would throw an error and quit anyways so is it really needed?

2017-01-16 20:49 UTC, mnzt commented on crypto/crypto.go
> +	derivedKey, _ := scrypt.Key(password, identifier, 1<<uint(costFactor["N"]), costFactor["r"], costFactor["p"], 32)
Validating user inputs is always a good thing - I doubt the scrypt error is very user friendly, either

2017-01-26 06:47 UTC, tobbbles requested changes

2017-01-26 06:47 UTC, mnzt commented on auxiliary/auxiliary.go
> +	ioutil.WriteFile("/home/awn/.pocket/secrets", []byte(jsonFormattedSecrets), 0700)
Change this.

Import `os/user` to get `u := user.Current()` and then use `u.HomeDir`. See https://godoc.org/os/user#User.

2017-01-26 06:47 UTC, mnzt commented on auxiliary/auxiliary_test.go
> +	args = []string{"./pocket", "get", "-c"}
Should should remove the `./` notation, as this wouldn't be present if the binary was in a users path

2017-01-26 07:03 UTC, libeclipse commented on auxiliary/auxiliary.go
> +	ioutil.WriteFile("/home/awn/.pocket/secrets", []byte(jsonFormattedSecrets), 0700)
We already do this.

2017-01-26 07:04 UTC, libeclipse commented on auxiliary/auxiliary_test.go
> +	args = []string{"./pocket", "get", "-c"}
It's being passed to a function that takes a slice of arguments, so it's not actually running anything, just emulating it being called with certain arguments.

2017-01-27 00:12 UTC, merged